---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    type: webserver
    author: cletus
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
      name: nginx-pod
      labels:
        type: webserver
        author: cletus
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...
